workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev"'
    - when: never

variables:
  APP_NAME: tradapi
  APP_URL: traducao2-dth.vlibras.lavid.ufpb.br

include:
  - project: 'vlibras2019/DevOps'
    ref: main
    file: '/Default-App-Pipeline-VLibras.gitlab-ci.yml'
