variables:
  APP_NAME: trad-api
  VALUES_LOCATION_EXTRA: "$VALUES_DEV"
  APP_URL: traducao2-dth.vlibras.lavid.ufpb.br

include:
  # 🔹 Template padrão para branches dev
  - project: 'vlibras2019/DevOps'
    ref: main
    file: '/Default-App-Pipeline-VLibras.gitlab-ci.yml'
    rules:
      - if: '$CI_COMMIT_REF_NAME == "dev"'
