apiVersion: v2
name: tradapi
description: API do Tradutor Vlibras.
maintainers:
  - name: Ministério da Gestão e Inovação em Serviços Públicos
    email: sgd@gestao.gov.br
type: application
version: 0.1.1
appVersion: "1.16.1"
keywords:
  - vlibras
  - backend
  - nodejs
  - redis
  - rabbitmq
  - postgresql