apiVersion: extensions/v1beta1
#kubectl expose deployment translatorapi --port=80 --type=LoadBalancer
kind: Deployment
metadata:
  name: translatorapi
  labels:
    app: translatorapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translatorapi
  template:
    metadata:
      labels:
        app: translatorapi
    spec:
      containers:
        - image: vlibras/translator-api:05
          name: translatorapi
          env:
            - name: AMQP_HOST
              value: "10.11.247.75"
            - name: AMQP_PORT
              value: "5672"
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "10.11.247.190"
            - name: DB_PORT
              value: "27017"
          ports:
            - containerPort: 80
              name: vlibras
          resources:
            requests:
              cpu: 600m
              memory: 1.5Gi
          #readinessProbe:
          #  httpGet:
          #    path: /healthcheck
          #    port: 80
          #  initialDelaySeconds: 30
          #  periodSeconds: 30
      hostNetwork: true

