apiVersion: "v1"
#gcloud compute disks create dicionario-disk --zone us-central1-a --size 30
kind: "PersistentVolume"
metadata:
  name: dicionario-pv
spec:
  capacity:
    storage: 30Gi 
  accessModes:
    - ReadWriteMany
  gcePersistentDisk: 
    fsType: ext4
    pdName: dicionario-disk
