// Timeout in milliseconds
export const CHANNEL_CLOSE_TIMEOUT = 500
export const TRANSLATION_TIMEOUT = 30000
export const TRANSLATION_MESSAGE_TTL = 30000
export const VIDEOGENERATION_TIMEOUT = 300000
export const VIDEOGENERATION_MESSAGE_TTL = 300000
