{{- if not .Values.tradapi.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "tradapi.fullname" . }}-app-secret'
  labels:
    {{ include "tradapi.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.tradapi.secrets.appSecret }}
  {{ $key | quote }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}